# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  # Pods for example2

  target 'example2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'example2UITests' do
    # Pods for testing
  end

end
