# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def sharePod
  pod 'FLAnimatedImage'
  pod 'SDWebImageSwiftUI'
end

use_frameworks!
target 'WBAnimatedSwiftUIViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  sharePod
  # Pods for WBAnimatedSwiftUIViewDemo
end

target 'MyWidgetExtension' do
  sharePod
end
